---
title: "notes-while-building"
author: "Rachit Kinger"
date: "6 September 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## QS Optimiation workflow  
### Output is:   

1. Which campaign(s) need keyword optimisation  
2. Which keyword(s) to be optimised in that campaign  
3. What is the priority of area of optimisation (i.e keywords, ad copy, landing page)  

### Input is**:  
1. .csv file downloaded from Google  
2. budget range of campaigns to consider (i.e. >£1000, >£500, between £300-£500)  

### Rules  
1. What is the campaign budget range? default = >£500 spend  `user defined`  
2. QS buckets  
    * `LQS` = 1,2,3    
    * `MQS` = 4,5,6  
    * `HQS` = 7,8,9,10  
3. What proportion of spend in each spectrum is worrisome? Default values are:  
    * `LQS` > 10%  
    * `MQS` > 30%  
    * `HQS` < 30%  
    * `LQS` > `MQS`  
4. In case of multiple rules being applied, which one is higher priority?  
5. Within each QS bucket which are the worrisom keywords? Default rule is:  
    * Whichever is higher of the two rules:  
        + Top 5 (in decreasing order of spend), or,  
        + Min. number of keywords required to make up at least 75% of spend in that category  
6. For the selected keywords what is the priority of suggested optimisation actions?  
    * Parameters and their performance indicators are:  
    
        Parameter                 | Indicator variable  
        ------------------------- | -----------------------  
        Keyword optimisation      | Expected CTR  
        Ad copy optimisation      | Ad copy relevance  
        Landing page optimisation | Landing page relevance
        
    * Rules are:  
        + whichever parameter's indicator is `below average` becomes the top priority  
        + whichever parameter's indicator is `average` becomes next in priority  
        + if there is a clash the following order prevails:  
            - Ad copy optimisation  
            - Keyword optimisation  
            - Landing page optimisation (can be ignored as well)  
            


